---
zhanqi.lgd_mmy:
- MMY
- lgd.MMY
zhanqi.Burning:
- Burning
- Burning
douyu.伊里野的天空:
- '伊里野的天空'
- iG.430
douyu.IG430:
- '430'
- iG.430
huomao.lanm2014:
- lanm
- lanm
douyu.Pc冷冷:
- 冷冷
- Dota2解说
douyu.igchuan:
- ChuaN
- iG.ChuaN
huomao.Oo老队长rOtK:
- rOtK
- rOtK
douyu.张宁_xiao8:
- xiao8
- xiao8
douyu.mushichai:
- MuShi
- EHOME.MuShi
douyu.yyfyyf:
- YYF
- RPG天团成员
douyu.a274951686:
- KINGJ
- KINGJ
douyu.luoyinqi:
- Luo
- iG.Luo
douyu.hyrx105:
- HyrX
- HyrX
douyu.ImbaTV直播:
- ImbaTV
- ImbaTV
douyu.hyhy汉勇:
- HYHY
- HYHY
douyu.waterater:
- 沐沐
- Dota2解说
douyu.念念Misa:
- 念念
- Dota2解说
zhanqi.sjq老鼠:
- 鼠大王
- 鼠大王
zhanqi.lilith♥:
- lilith
- lilith
zhanqi.lgd_yao:
- Yao
- lgd.Yao
huomao.NewBeeTV:
- NewBeeTV
- NewBeeTV
huomao.VG.Black:
- Black
- vg.Black
huomao.VG.fyfy:
- fy
- vg.fy
huomao.赵洁Leah:
- 赵洁
- 赵洁
huomao.yanghanna:
- Yang Hanna
- Yang Hanna
zhanqi.伍声 2009:
- '2009'
- 前DOTA职业选手, 现任电竞视频解说, 淘宝卖家
huomao.MarsTV官方:
- MarsTV
- MarsTV官方
huomao.MarsTV官方频道2:
- MarsTV2
- MarsTV官方频道2
huomao.LV妖精Zyf:
- 妖精
- EHOME.妖精
huomao.inflamelol:
- Inflame
- EHOME.Inflame
huomao.LGDTV直播间:
- LGDTV
- LGDTV是LGD电子竞技俱乐部旗下专业赛事直播平台
huomao.huomaoTV官方:
- huomaoTV
- huomaoTV官方
huomao.huomaoTV官方2:
- huomaoTV2
- huomaoTV官方2
huomao.雅少萌萌哒:
- 陈雅
- Dota2解说
huomao.NWP:
- YamateH
- Y神
huomao.教练mikasa:
- 教练
- cdec.mikasa
huomao.VG.super:
- super
- vg.super
zhanqi.安娜萌萌哒✿:
- 安娜
- 安娜萌萌哒✿
zhanqi.Yomi丶酸奶:
- Yomi丶酸奶
- Yomi丶酸奶
zhanqi.✿﹏Yuno酱:
- "✿﹏Yuno酱"
- "✿﹏Yuno酱"
zhanqi.lgd_Sylar:
- Sylar
- lgd.sylar
zhanqi.lgd_Faith:
- Faith
- lgd.Faith
zhanqi.lgd_injuly:
- injuly
- lgd.injuly
zhanqi.傻瓜立:
- li
- Newbee.Li
zhanqi.Newbee_Banana:
- Banana
- Newbee.Banana
zhanqi.Newbee_Hao:
- Hao
- Newbee.Hao
zhanqi.Newbee_Mu:
- Mu
- Newbee.Mu
zhanqi.Newbee_SanSheng:
- SanSheng
- Newbee.SanSheng
zhanqi.王章:
- Rabbit
- Newbee.Rabbit
douyu.ctyzzz:
- Cty
- DK.Cty
douyu.杰出哥:
- 杰出
- 斗鱼解说
douyu.stormall:
- HGT
- HGT直播
douyu.ZSMJ727974758:
- ZSMJ
- HGT.ZSMJ
douyu.452123262:
- 陈世美
- HGT.kaka
